apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry
  namespace: kube-system
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.33.9.42
    path: "/srv/docker-registry"
