kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-registry
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: docker-registry
