apiVersion: v1
kind: PersistentVolume
metadata:
  name: rbd-demo1
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - f25rbd:6789
    pool: rbd
    image: demo1
    user: admin
    secretRef:
      name: rbdadmin
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: rbd-demo1
