apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: libvirt
  namespace: libvirt-kube
  labels:
    name: libvirt-kube
spec:
  template:
    metadata:
      labels:
        app: libvirt-kube
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: libvirtkubevirtd
        image: localhost:5000/libvirtkubevirtd
        ports:
        - name: libvirttls
          containerPort: 16514
          hostPort: 16514
        env:
        - name: LIBVIRT_LOG_FILTERS
          value: 1:qemu 1:process
        - name: LIBVIRT_LOG_OUTPUTS
          value: 1:stderr
        volumeMounts:
        - name: virtdx509ca
          mountPath: /etc/pki/CA/libvirt
          readOnly: true
        - name: libvirt
          mountPath: /srv/libvirt
        - name: dbus
          mountPath: /run/dbus
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: shared-images
          mountPath: /srv/images/shared-images
        securityContext:
          privileged: true
      - name: libvirtkubevirtlogd
        image: localhost:5000/libvirtkubevirtlogd
        volumeMounts:
        - name: libvirt
          mountPath: /srv/libvirt
        securityContext:
          privileged: true
#      - name: libvirtkubevirtlockd
#        image: localhost:5000/libvirtkubevirtlockd
      volumes:
      - name: virtdx509ca
        secret:
          secretName: virtdx509ca
      - name: libvirt
        hostPath:
          path: /srv/libvirt
      - name: dbus
        hostPath:
          path: /run/dbus
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: shared-images
        nfs:
          server: 10.33.9.42
          path: /srv/shared-images
