apiVersion: v1
kind: Pod
metadata:
  name: virtkubevmshim
  namespace: libvirt-kube
spec:
  hostPID: true
  containers:
    - name: libvirtkubevmshim
      image: localhost:5000/libvirtkubevmshim
      args:
        - /usr/local/bin/virtkubevmshim
        - --logtostderr
        - -v
        - "1"
      volumeMounts:
        - mountPath: /run/libvirt
          name: libvirt
        - mountPath: /run/virtkubevmshim
          name: vmshim
  volumes:
    - name: libvirt
      hostPath:
        path: /srv/libvirt/run
    - name: vmshim
      hostPath:
        path: /srv/vmshim
